[project]
name = "conversation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.2",
    "numpy>=1.26.0",
    "pydantic-ai>=1.62.0",
    "uvicorn>=0.41.0",
]
